events { worker_connections 1024;}

http {
    # Define upstream block for round-robin load balancing between our two backends
    upstream backend_pool {
        server 127.0.0.1:3001;
        server 127.0.0.1:3002;
    }

    server {
        # listen 8443 ssl;
        listen 80;
        server_name app.team1.test;

        # SSL Certificates generated via mkcert
        # ssl_certificate /Users/palakgupta/path-to-your-cert/app.team1.test.pem;
        # ssl_certificate_key /Users/palakgupta/path-to-your-cert/app.team1.test-key.pem;

        location / {
            proxy_pass http://backend_pool;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            
            # Pass custom header from upstream to client
            add_header X-Backend $upstream_http_x_backend;
        }
    }
}